app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/spring-jdbc
      password: 'postgres_pass'
      pool-size: 30
      username: postgres_user

server:
  error:
    include-binding-errors: always
    include-message: always


